import Layout from '@/components/Layout'
import { Logo } from '@/components/Logo'
import {
  Flex,
  Text,
  Card,
  CardBody,
  Stack,
  Heading,
  CardFooter,
  Button,
  Divider,
  Icon,
  useToast,
} from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'

import { PiSealCheckBold } from 'react-icons/pi'

import ImageProduct from '../assets/products/moletom-ai-side.png'
import QRCode from '@/components/QRCode'
import axios from 'axios'

export default function Home() {
  const toast = useToast()

  const [isLoading, setIsLoading] = useState(false)
  const [checkoutCreated, setCheckoutCreated] = useState(false)

  const [qrCode, setQRCode] = useState('')

  const handleCreateCheckout = async () => {
    setIsLoading(true)

    const data = {
      email: 'user@test.com.br',
      firstName: 'Usuário',
      lastName: 'Test',
      price: 50,
      quantity: 1,
    }

    try {
      const response = await axios.post(
        '/api/mercado-pago/create-checkout',
        data,
      )

      const code = response.data.code
      if (code) {
        setQRCode(code)
        setCheckoutCreated(true)
      }
    } catch (error) {
      console.log(error)

      toast({
        title: 'Ops! Ocorreu algum erro',
        position: 'top-right',
        isClosable: true,
        status: 'error',
      })
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <>
      <Head>
        <title>Pagamento via QR Code - Laboratório</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/lab-tool.png" />
      </Head>

      <Layout>
        <Flex
          w={{
            base: '100%',
            lg: '550px',
          }}
          maxW="550"
          h={{
            base: 'auto',
            lg: '785px',
          }}
          maxH="900"
          align="center"
          direction="column"
          borderRadius="6"
          bg="gray.800"
          px={{
            base: '4',
            lg: '8',
          }}
          py="4"
          gap="4"
          boxShadow="2xl"
        >
          <Flex direction="row" align="center" w="100%" justify="space-between">
            <Logo />

            <Text
              fontSize={{
                base: '16',
                lg: '20',
              }}
              fontWeight="semibold"
            >
              Realize seu pagamento
            </Text>
          </Flex>

          {!checkoutCreated ? (
            <Card
              w="100%"
              border="1px solid"
              borderColor="gray.700"
              bg="transparent"
            >
              <CardBody>
                <Image
                  src={ImageProduct}
                  alt="Imagem do produto"
                  placeholder="blur"
                  blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNM3q1aDwAEkAHENSZfHAAAAABJRU5ErkJggg=="
                  priority
                />

                <Stack mt="6" spacing="2">
                  <Heading color="gray.400" fontWeight="light" size="sm">
                    Pedido #5317
                  </Heading>

                  <Text
                    fontWeight="semibold"
                    color="whatsapp.500"
                    fontSize={{
                      base: '24',
                      lg: '30',
                    }}
                  >
                    R$ 50,00
                  </Text>
                </Stack>
              </CardBody>

              <Divider />

              <CardFooter>
                <Flex
                  w="100%"
                  direction={{
                    base: 'column-reverse',
                    lg: 'row',
                  }}
                  align="center"
                  justify="space-between"
                  gap={{
                    base: '4',
                    lg: 'unset',
                  }}
                >
                  <Flex direction="row" align="center" color="gray.500" gap="1">
                    <Text
                      as="span"
                      fontSize={{
                        base: '12',
                        lg: '14',
                      }}
                    >
                      Pagamento através do Mercado Pago
                    </Text>
                    <Icon as={PiSealCheckBold} />
                  </Flex>

                  <Button
                    colorScheme="whatsapp"
                    color="blackAlpha.900"
                    bg="whatsapp.500"
                    isLoading={isLoading}
                    onClick={handleCreateCheckout}
                  >
                    Pagar agora
                  </Button>
                </Flex>
              </CardFooter>
            </Card>
          ) : (
            <QRCode isLoading={isLoading} code={qrCode} />
          )}
        </Flex>
      </Layout>
    </>
  )
}
